touch blockLists/alwaysAllowStartsWithUrl.txt
touch blockLists/blockAllTabsIfUrlOpen.txt
touch blockLists/blockedDomains.txt
touch blockLists/blockedStartsWithUrl.txt
touch blockLists/regexBlock.txt
touch blockLists/blockedRequestInitiator.txt
